
// Code generated by stanc 3032660f
#include <stan/model/model_header.hpp>
namespace ventilator_model_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 98, column 2 to column 18)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 99, column 2 to column 25)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 100, column 2 to column 20)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 108, column 2 to column 35)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 109, column 2 to line 111, column 70)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 115, column 2 to column 27)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 116, column 2 to column 41)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 117, column 2 to column 31)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 132, column 4 to column 36)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 133, column 4 to column 36)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 134, column 4 to column 36)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 131, column 19 to line 135, column 3)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 131, column 2 to line 135, column 3)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 71, column 2 to column 19)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 72, column 14 to column 17)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 72, column 2 to column 19)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 73, column 10 to column 13)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 73, column 2 to column 15)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 74, column 2 to column 14)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 75, column 2 to column 21)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 76, column 2 to column 16)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 78, column 2 to column 10)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 79, column 2 to column 10)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 80, column 2 to column 10)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 81, column 2 to column 12)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 82, column 2 to column 17)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 83, column 2 to column 22)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 87, column 2 to column 27)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 88, column 2 to column 48)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 89, column 2 to column 52)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 91, column 2 to column 16)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 109, column 17 to column 20)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 8, column 4 to column 18)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 12, column 6 to column 18)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 11, column 9 to line 12, column 18)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 10, column 6 to column 17)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 9, column 4 to line 12, column 18)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 14, column 4 to column 48)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 15, column 4 to column 17)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 7, column 42 to line 16, column 3)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 29, column 4 to column 19)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 31, column 4 to column 17)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 32, column 4 to column 19)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 33, column 4 to column 15)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 35, column 4 to column 29)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 36, column 4 to column 25)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 37, column 4 to column 21)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 39, column 4 to column 46)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 41, column 4 to column 47)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 59, column 6 to column 21)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 60, column 6 to column 52)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 61, column 6 to column 36)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 58, column 9 to line 62, column 5)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 54, column 6 to column 21)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 55, column 6 to column 51)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 56, column 6 to column 42)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 53, column 51 to line 57, column 5)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 53, column 9 to line 62, column 5)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 49, column 6 to column 18)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 50, column 6 to column 16)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 51, column 6 to column 69)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 48, column 46 to line 52, column 5)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 48, column 9 to line 62, column 5)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 44, column 6 to column 21)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 45, column 6 to column 74)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 46, column 6 to column 42)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 43, column 27 to line 47, column 5)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 43, column 4 to line 62, column 5)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 64, column 4 to column 40)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 66, column 4 to column 16)",
                                                      " (in 'C:/Users/brara/projects/ventilator/models/ventilator_model.stan', line 28, column 30 to line 67, column 3)"};


template <typename T0__, typename T1__, typename T2__, typename T3__>
stan::promote_args_t<T0__, T1__, T2__,
T3__>
flow_function(const T0__& t, const T1__& insp_time, const T2__& const_flow,
              const T3__& flow_rise_time, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    local_scalar_t__ sign;
    sign = DUMMY_VAR__;
    
    current_statement__ = 33;
    sign = 0;
    current_statement__ = 37;
    if (logical_lte(t, flow_rise_time)) {
      current_statement__ = 36;
      sign = 1.0;
    } else {
      current_statement__ = 35;
      if (logical_gte(t, (insp_time - flow_rise_time))) {
        current_statement__ = 34;
        sign = -1.0;
      } 
    }
    local_scalar_t__ dFlow;
    dFlow = DUMMY_VAR__;
    
    current_statement__ = 38;
    dFlow = ((sign * const_flow) / flow_rise_time);
    current_statement__ = 39;
    return dFlow;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}

struct flow_function_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__>
stan::promote_args_t<T0__, T1__, T2__,
T3__>
operator()(const T0__& t, const T1__& insp_time, const T2__& const_flow,
           const T3__& flow_rise_time, std::ostream* pstream__)  const 
{
return flow_function(t, insp_time, const_flow, flow_rise_time, pstream__);
}
};

template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__, typename T5__, typename T6__, typename T7__, typename T8__,
typename T9__, typename T10__>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T2__, T3__, T4__, stan::promote_args_t<T5__,
T6__, T7__, T8__,
T9__, stan::promote_args_t<T10__>>>, -1, 1>
ventilator(const T0__& t, const Eigen::Matrix<T1__, -1, 1>& y, const T2__& R,
           const T3__& C_static, const T4__& insp_time,
           const T5__& const_flow, const T6__& flow_rise_time,
           const T7__& breath_time, const T8__& hold_time, const T9__& peep,
           const T10__& frc, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          T1__,
          T2__,
          T3__,
          T4__, stan::promote_args_t<T5__,
          T6__,
          T7__,
          T8__,
          T9__, stan::promote_args_t<T10__>>>;
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    Eigen::Matrix<local_scalar_t__, -1, 1> dydt;
    dydt = Eigen::Matrix<local_scalar_t__, -1, 1>(3);
    stan::math::fill(dydt, DUMMY_VAR__);
    
    local_scalar_t__ dVolume;
    dVolume = DUMMY_VAR__;
    
    local_scalar_t__ dPressure;
    dPressure = DUMMY_VAR__;
    
    local_scalar_t__ dFlow;
    dFlow = DUMMY_VAR__;
    
    local_scalar_t__ volume;
    volume = DUMMY_VAR__;
    
    current_statement__ = 45;
    volume = (y[(1 - 1)] - frc);
    local_scalar_t__ pressure;
    pressure = DUMMY_VAR__;
    
    current_statement__ = 46;
    pressure = y[(2 - 1)];
    local_scalar_t__ flow;
    flow = DUMMY_VAR__;
    
    current_statement__ = 47;
    flow = y[(3 - 1)];
    local_scalar_t__ num_breaths;
    num_breaths = DUMMY_VAR__;
    
    current_statement__ = 48;
    num_breaths = stan::math::floor((t / breath_time));
    local_scalar_t__ mod_t;
    mod_t = DUMMY_VAR__;
    
    current_statement__ = 49;
    mod_t = (t - (num_breaths * breath_time));
    current_statement__ = 68;
    if (logical_lt(mod_t, insp_time)) {
      current_statement__ = 64;
      dVolume = flow;
      current_statement__ = 65;
      dFlow = flow_function(mod_t, insp_time, const_flow,
                flow_rise_time, pstream__);
      current_statement__ = 66;
      dPressure = ((flow / C_static) + (R * dFlow));
    } else {
      current_statement__ = 63;
      if (logical_lt(mod_t, (insp_time + hold_time))) {
        current_statement__ = 59;
        dVolume = 0;
        current_statement__ = 60;
        dFlow = 0;
        current_statement__ = 61;
        dPressure = (((-pressure + (volume / C_static)) + peep) /
                      (R * C_static));
      } else {
        current_statement__ = 58;
        if (logical_lt(mod_t, ((insp_time + hold_time) + 0.02))) {
          current_statement__ = 54;
          dVolume = flow;
          current_statement__ = 55;
          dPressure = ((-pressure + peep) / (R * C_static));
          current_statement__ = 56;
          dFlow = ((-volume / (R * C_static)) / 0.02);
        } else {
          current_statement__ = 50;
          dVolume = flow;
          current_statement__ = 51;
          dPressure = ((-pressure + peep) / (R * C_static));
          current_statement__ = 52;
          dFlow = (-flow / (R * C_static));
        }
      }
    }
    current_statement__ = 69;
    assign(dydt, nil_index_list(),
      transpose(stan::math::to_row_vector(
        stan::math::array_builder<local_scalar_t__>().add(dVolume)
        .add(dPressure).add(dFlow).array())), "assigning variable dydt");
    current_statement__ = 70;
    return dydt;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}

struct ventilator_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__, typename T5__, typename T6__, typename T7__, typename T8__,
typename T9__, typename T10__>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T2__, T3__, T4__, stan::promote_args_t<T5__,
T6__, T7__, T8__,
T9__, stan::promote_args_t<T10__>>>, -1, 1>
operator()(const T0__& t, const Eigen::Matrix<T1__, -1, 1>& y, const T2__& R,
           const T3__& C_static, const T4__& insp_time,
           const T5__& const_flow, const T6__& flow_rise_time,
           const T7__& breath_time, const T8__& hold_time, const T9__& peep,
           const T10__& frc, std::ostream* pstream__)  const 
{
return ventilator(t, y, R, C_static, insp_time, const_flow, flow_rise_time,
         breath_time, hold_time, peep, frc, pstream__);
}
};


struct ventilator_odefunctor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__, typename T5__, typename T6__, typename T7__, typename T8__,
typename T9__, typename T10__>
Eigen::Matrix<stan::promote_args_t<T0__, T1__, T2__, T3__, T4__, stan::promote_args_t<T5__,
T6__, T7__, T8__,
T9__, stan::promote_args_t<T10__>>>, -1, 1>
operator()(const T0__& t, const Eigen::Matrix<T1__, -1, 1>& y,
           std::ostream* pstream__, const T2__& R, const T3__& C_static,
           const T4__& insp_time, const T5__& const_flow,
           const T6__& flow_rise_time, const T7__& breath_time,
           const T8__& hold_time, const T9__& peep, const T10__& frc)  const 
{
return ventilator(t, y, R, C_static, insp_time, const_flow, flow_rise_time,
         breath_time, hold_time, peep, frc, pstream__);
}
};

class ventilator_model_model final : public model_base_crtp<ventilator_model_model> {

 private:
  int N_t;
  std::vector<Eigen::Matrix<double, -1, 1>> y;
  std::vector<double> ts;
  double mean_R;
  double mean_C_static;
  double mean_frc;
  double RR;
  double IE;
  double VT;
  double peep;
  double hold_time;
  double flow_rise_time;
  double breath_time;
  double insp_time;
  double const_flow;
  double t0;
 
 public:
  ~ventilator_model_model() final { }
  
  std::string model_name() const final { return "ventilator_model_model"; }

  std::vector<std::string> model_compile_info() const {
    std::vector<std::string> stanc_info;
    stanc_info.push_back("stanc_version = stanc3 3032660f");
    stanc_info.push_back("stancflags = ");
    return stanc_info;
  }
  
  
  ventilator_model_model(stan::io::var_context& context__,
                         unsigned int random_seed__ = 0,
                         std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "ventilator_model_model_namespace::ventilator_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","N_t","int",
          context__.to_vec());
      N_t = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      N_t = context__.vals_i("N_t")[(1 - 1)];
      current_statement__ = 14;
      current_statement__ = 14;
      check_greater_or_equal(function__, "N_t", N_t, 0);
      current_statement__ = 15;
      validate_non_negative_index("y", "N_t", N_t);
      current_statement__ = 16;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(N_t, 3));
      y = std::vector<Eigen::Matrix<double, -1, 1>>(N_t, Eigen::Matrix<double, -1, 1>(3));
      stan::math::fill(y, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 16;
        assign(y_flat__, nil_index_list(), context__.vals_r("y"),
          "assigning variable y_flat__");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 16;
          for (int sym2__ = 1; sym2__ <= N_t; ++sym2__) {
            current_statement__ = 16;
            assign(y,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              y_flat__[(pos__ - 1)], "assigning variable y");
            current_statement__ = 16;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 17;
      validate_non_negative_index("ts", "N_t", N_t);
      current_statement__ = 18;
      context__.validate_dims("data initialization","ts","double",
          context__.to_vec(N_t));
      ts = std::vector<double>(N_t, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 18;
      assign(ts, nil_index_list(), context__.vals_r("ts"),
        "assigning variable ts");
      current_statement__ = 19;
      context__.validate_dims("data initialization","mean_R","double",
          context__.to_vec());
      mean_R = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 19;
      mean_R = context__.vals_r("mean_R")[(1 - 1)];
      current_statement__ = 20;
      context__.validate_dims("data initialization","mean_C_static","double",
          context__.to_vec());
      mean_C_static = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 20;
      mean_C_static = context__.vals_r("mean_C_static")[(1 - 1)];
      current_statement__ = 21;
      context__.validate_dims("data initialization","mean_frc","double",
          context__.to_vec());
      mean_frc = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 21;
      mean_frc = context__.vals_r("mean_frc")[(1 - 1)];
      current_statement__ = 22;
      context__.validate_dims("data initialization","RR","double",
          context__.to_vec());
      RR = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 22;
      RR = context__.vals_r("RR")[(1 - 1)];
      current_statement__ = 23;
      context__.validate_dims("data initialization","IE","double",
          context__.to_vec());
      IE = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 23;
      IE = context__.vals_r("IE")[(1 - 1)];
      current_statement__ = 24;
      context__.validate_dims("data initialization","VT","double",
          context__.to_vec());
      VT = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 24;
      VT = context__.vals_r("VT")[(1 - 1)];
      current_statement__ = 25;
      context__.validate_dims("data initialization","peep","double",
          context__.to_vec());
      peep = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 25;
      peep = context__.vals_r("peep")[(1 - 1)];
      current_statement__ = 26;
      context__.validate_dims("data initialization","hold_time","double",
          context__.to_vec());
      hold_time = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 26;
      hold_time = context__.vals_r("hold_time")[(1 - 1)];
      current_statement__ = 27;
      context__.validate_dims("data initialization","flow_rise_time",
          "double",context__.to_vec());
      flow_rise_time = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 27;
      flow_rise_time = context__.vals_r("flow_rise_time")[(1 - 1)];
      current_statement__ = 28;
      breath_time = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 28;
      breath_time = (60 / RR);
      current_statement__ = 29;
      insp_time = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 29;
      insp_time = ((1.0 / (1.0 + IE)) * breath_time);
      current_statement__ = 30;
      const_flow = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 30;
      const_flow = (VT / (insp_time - flow_rise_time));
      current_statement__ = 31;
      t0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 31;
      t0 = 0.0;
      current_statement__ = 32;
      validate_non_negative_index("y_mu", "N_t", N_t);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  inline T__ log_prob(std::vector<T__>& params_r__,
                      std::vector<int>& params_i__,
                      std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "ventilator_model_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      local_scalar_t__ R;
      R = DUMMY_VAR__;
      
      current_statement__ = 1;
      R = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        R = stan::math::lb_constrain(R, 0, lp__);
      } else {
        current_statement__ = 1;
        R = stan::math::lb_constrain(R, 0);
      }
      local_scalar_t__ C_static;
      C_static = DUMMY_VAR__;
      
      current_statement__ = 2;
      C_static = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        C_static = stan::math::lb_constrain(C_static, 0, lp__);
      } else {
        current_statement__ = 2;
        C_static = stan::math::lb_constrain(C_static, 0);
      }
      local_scalar_t__ frc;
      frc = DUMMY_VAR__;
      
      current_statement__ = 3;
      frc = in__.scalar();
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        frc = stan::math::lb_constrain(frc, 0, lp__);
      } else {
        current_statement__ = 3;
        frc = stan::math::lb_constrain(frc, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> y0;
      y0 = Eigen::Matrix<local_scalar_t__, -1, 1>(3);
      stan::math::fill(y0, DUMMY_VAR__);
      
      current_statement__ = 4;
      assign(y0, nil_index_list(),
        transpose(stan::math::to_row_vector(
          stan::math::array_builder<local_scalar_t__>().add(frc).add(peep)
          .add(0.0).array())), "assigning variable y0");
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> y_mu;
      y_mu = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(N_t, Eigen::Matrix<local_scalar_t__, -1, 1>(3));
      stan::math::fill(y_mu, DUMMY_VAR__);
      
      current_statement__ = 5;
      assign(y_mu, nil_index_list(),
        ode_rk45(ventilator_odefunctor__(), y0, t0, ts, pstream__, R,
          C_static, insp_time, const_flow, flow_rise_time, breath_time,
          hold_time, peep, frc), "assigning variable y_mu");
      {
        current_statement__ = 6;
        lp_accum__.add(gamma_lpdf<propto__>(R, (10 * mean_R), 10));
        current_statement__ = 7;
        lp_accum__.add(
          gamma_lpdf<propto__>(C_static, (10 * mean_C_static), 10));
        current_statement__ = 8;
        lp_accum__.add(gamma_lpdf<propto__>(frc, (10 * mean_frc), 10));
        current_statement__ = 13;
        for (int t = 1; t <= N_t; ++t) {
          current_statement__ = 9;
          lp_accum__.add(
            normal_lpdf<propto__>(y[(t - 1)][(1 - 1)],
              y_mu[(t - 1)][(1 - 1)], 1));
          current_statement__ = 10;
          lp_accum__.add(
            normal_lpdf<propto__>(y[(t - 1)][(2 - 1)],
              y_mu[(t - 1)][(2 - 1)], 1));
          current_statement__ = 11;
          lp_accum__.add(
            normal_lpdf<propto__>(y[(t - 1)][(3 - 1)],
              y_mu[(t - 1)][(3 - 1)], 1));}
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  inline void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                          std::vector<int>& params_i__,
                          std::vector<double>& vars__,
                          bool emit_transformed_parameters__ = true,
                          bool emit_generated_quantities__ = true,
                          std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "ventilator_model_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double R;
      R = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      R = in__.scalar();
      current_statement__ = 1;
      R = stan::math::lb_constrain(R, 0);
      double C_static;
      C_static = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      C_static = in__.scalar();
      current_statement__ = 2;
      C_static = stan::math::lb_constrain(C_static, 0);
      double frc;
      frc = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      frc = in__.scalar();
      current_statement__ = 3;
      frc = stan::math::lb_constrain(frc, 0);
      Eigen::Matrix<double, -1, 1> y0;
      y0 = Eigen::Matrix<double, -1, 1>(3);
      stan::math::fill(y0, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<Eigen::Matrix<double, -1, 1>> y_mu;
      y_mu = std::vector<Eigen::Matrix<double, -1, 1>>(N_t, Eigen::Matrix<double, -1, 1>(3));
      stan::math::fill(y_mu, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(R);
      vars__.emplace_back(C_static);
      vars__.emplace_back(frc);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 4;
      assign(y0, nil_index_list(),
        transpose(stan::math::to_row_vector(
          stan::math::array_builder<local_scalar_t__>().add(frc).add(peep)
          .add(0.0).array())), "assigning variable y0");
      current_statement__ = 5;
      assign(y_mu, nil_index_list(),
        ode_rk45(ventilator_odefunctor__(), y0, t0, ts, pstream__, R,
          C_static, insp_time, const_flow, flow_rise_time, breath_time,
          hold_time, peep, frc), "assigning variable y_mu");
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          vars__.emplace_back(y0[(sym1__ - 1)]);}
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N_t; ++sym2__) {
            vars__.emplace_back(y_mu[(sym2__ - 1)][(sym1__ - 1)]);}}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  inline void transform_inits(const stan::io::var_context& context__,
                              std::vector<int>& params_i__,
                              std::vector<double>& vars__,
                              std::ostream* pstream__) const
    final {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double R;
      R = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      R = context__.vals_r("R")[(1 - 1)];
      current_statement__ = 1;
      R = stan::math::lb_free(R, 0);
      double C_static;
      C_static = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      C_static = context__.vals_r("C_static")[(1 - 1)];
      current_statement__ = 2;
      C_static = stan::math::lb_free(C_static, 0);
      double frc;
      frc = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      frc = context__.vals_r("frc")[(1 - 1)];
      current_statement__ = 3;
      frc = stan::math::lb_free(frc, 0);
      vars__.emplace_back(R);
      vars__.emplace_back(C_static);
      vars__.emplace_back(frc);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("R");
    names__.emplace_back("C_static");
    names__.emplace_back("frc");
    names__.emplace_back("y0");
    names__.emplace_back("y_mu");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const
    final {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(3)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N_t),
                                             static_cast<size_t>(3)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "R");
    param_names__.emplace_back(std::string() + "C_static");
    param_names__.emplace_back(std::string() + "frc");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y0" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N_t; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "y_mu" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "R");
    param_names__.emplace_back(std::string() + "C_static");
    param_names__.emplace_back(std::string() + "frc");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y0" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N_t; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "y_mu" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"R\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"C_static\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"frc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y0\",\"type\":{\"name\":\"vector\",\"length\":" << 3 << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_mu\",\"type\":{\"name\":\"array\",\"length\":" << N_t << ",\"element_type\":{\"name\":\"vector\",\"length\":" << 3 << "}},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"R\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"C_static\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"frc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y0\",\"type\":{\"name\":\"vector\",\"length\":" << 3 << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_mu\",\"type\":{\"name\":\"array\",\"length\":" << N_t << ",\"element_type\":{\"name\":\"vector\",\"length\":" << 3 << "}},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = nullptr) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = nullptr) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__ = nullptr) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}
using stan_model = ventilator_model_model_namespace::ventilator_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


